Repository immersion-juliet-misfits/playcation, pull requests merged in 2024-07, with the labels that each got.

#17 Homepage navigation
  client/index.html
  client/src/components/App.jsx
  client/src/components/Homepage.jsx
  client/src/components/NavDrawer.jsx
  client/src/components/planning/Planner.jsx
Labels: good first issue

#20 Passport added routes for login and logout, and authentication request
  .env.example
  client/src/components/App.jsx
  client/src/components/Homepage.jsx
  client/src/components/Login.jsx
  client/src/components/NavDrawer.jsx
  package.json
  server/db/index.js
  server/index.js
  server/middleware/auth.js
  server/routes/routes.js
  server/routes/userController.js
Labels: invalid

#18 Add CommunityPage component
  .env.example
  client/src/components/App.jsx
  client/src/components/community/CommunityFeed.jsx
  client/src/components/community/CommunityInput.jsx
  client/src/components/community/CommunityPage.jsx
  client/src/components/community/CommunityPost.jsx
  package.json
  server/db/index.js
  server/index.js
  server/routes/communityRoutes/community.js
Labels: invalid

#27 Community / Main CRUD implemented
  client/index.html
  client/src/components/App.jsx
  client/src/components/Homepage.jsx
  client/src/components/community/CommunityFeed.jsx
  client/src/components/community/CommunityInput.jsx
  client/src/components/community/CommunityPage.jsx
  client/src/components/community/CommunityPost.jsx
  client/src/components/community/ImageUpload.jsx
  package.json
  server/db/index.js
  server/routes/communityRoutes/community.js
  webpack.config.js
Labels: enhancement

#19 added style with mui to make the Reviews look a bit better
  .env.example
  .gitignore
  client/src/components/App.jsx
  client/src/components/Homepage.jsx
  client/src/components/reviews/AddReview.jsx
  client/src/components/reviews/Reviews.jsx
  client/src/components/reviews/UpdataReview.jsx
  server/db/index.js
  server/index.js
  server/routes/reviewsRoutes.js
Labels: good first issue

#32 Update feat / Community
  client/index.html
  client/src/components/App.jsx
  client/src/components/community/CommunityFeed.jsx
  client/src/components/community/CommunityInput.jsx
  client/src/components/community/CommunityPage.jsx
  client/src/components/community/CommunityPost.jsx
  client/src/components/community/ImageUpload.jsx
  server/db/index.js
  server/index.js
  server/routes/communityRoutes/community.js
  server/routes/communityRoutes/yelpApi.js
Labels: invalid

#24 Planner page
  client/src/components/App.jsx
  client/src/components/Search.jsx
  client/src/components/community/CommunityPost.jsx
  client/src/components/planning/Planner.jsx
  client/src/components/planning/PlannerDisplays.jsx
  client/src/components/planning/PlannerSearch.jsx
  client/src/components/planning/buttonSelect.jsx
  client/src/components/planning/createPlanner.jsx
  client/src/components/planning/displaySelect.jsx
  client/src/components/planning/tableSelect.jsx
  server/db/index.js
  server/db/plan_fData.js
  server/routes/communityRoutes/community.js
  server/routes/plannerController.js
  server/routes/plannerRoutes/plannerController.js
  server/routes/profileController.js
  server/routes/reviewsRoutes.js
  server/routes/routes.js
Labels: enhancement
